services:
  - type: web
    name: safar
    runtime: python
    buildCommand: bash ./render_build.sh
    startCommand: gunicorn --worker-class gthread --threads 100 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: change_me_in_production
